
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  age int,
  major text,
  year text,
  hostel text,
  bio text,
  verified boolean default false,
  avatar_url text,
  gallery text[], -- Array of image URLs
  interests jsonb, -- Store icons/labels as JSON
  looking_for jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SWIPES
create table swipes (
  id bigint generated by default as identity primary key,
  swiper_id uuid references profiles(id) not null,
  target_id uuid references profiles(id) not null,
  action text check (action in ('like', 'pass')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(swiper_id, target_id)
);

-- MATCHES
create table matches (
  id bigint generated by default as identity primary key,
  user1_id uuid references profiles(id) not null,
  user2_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user1_id, user2_id)
);

-- MESSAGES
create table messages (
  id bigint generated by default as identity primary key,
  match_id bigint references matches(id) not null,
  sender_id uuid references profiles(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
alter table profiles enable row level security;
alter table swipes enable row level security;
alter table matches enable row level security;
alter table messages enable row level security;

-- Policies (Simplified for demo, refine for production)
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Users can insert their own swipes" on swipes for insert with check (auth.uid() = swiper_id);
-- Match visibility: User is one of the participants
create policy "Users see their matches" on matches for select using (auth.uid() = user1_id or auth.uid() = user2_id);

-- Message visibility
create policy "Users see messages in their matches" on messages for select using (
  exists (select 1 from matches m where m.id = match_id and (m.user1_id = auth.uid() or m.user2_id = auth.uid()))
);
create policy "Users send messages to their matches" on messages for insert with check (
  exists (select 1 from matches m where m.id = match_id and (m.user1_id = auth.uid() or m.user2_id = auth.uid()))
);

-- Function to handle new user signup (Trigger)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
